### ISSUE TITLE
"Error in migration engine" Mysql Remote Database

### ISSUE THREAD

**Issue by thankwsx** [prisma/lift#248]
my `schema.prisma` file
```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "mysql"
  url = "mysql://root:xxxxxxxx@xxxxxxxx.cn:xxxxxx/DATABASE"
}

model t_feeds {
  xxx
}

model t_shareinfo {
  Fcategory String @default("unknown")
  .....
}
```

console text:

Reason: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/io/driver/mod.rs:243:21] no current reactor

Please create an issue in the lift repo with
your `schema.prisma` and the prisma2 command you tried to use 🙏:
https://github.com/prisma/lift/issues/new

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/prisma2/build/index.js:172365:35)
    at ChildProcess.emit (events.js:219:5)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)

**Comment by janpio** [comment]
Thanks for reporting @thankwsx, specific reason why you closed it again?
