### ISSUE TITLE
`prisma2 lift docs` does not work

### ISSUE THREAD

**Issue by mavilein** [prisma/lift#37]
results in:
```
➜  next git:(master) prisma2 lift docs
Error:
! Unknown command "docs"
...
at Object.unknownCommand (/usr/local/lib/node_modules/prisma2/build/index.js:326152:12)
    at LiftCommand.<anonymous> (/usr/local/lib/node_modules/prisma2/build/index.js:387568:26)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/prisma2/build/index.js:387529:71
    at new Promise (<anonymous>)
    at module.exports.9830.__awaiter (/usr/local/lib/node_modules/prisma2/build/index.js:387525:12)
    at LiftCommand.parse (/usr/local/lib/node_modules/prisma2/build/index.js:387550:16)
    at CLI.<anonymous> (/usr/local/lib/node_modules/prisma2/build/index.js:160366:28)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/prisma2/build/index.js:160324:71
```

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
